// import './Strategy';
// import './Observer';
// import './Decorator';
// import './FactoryMethod';
// import './AbstractFactory';
// import './Singleton';
// import './Command';
// import './Adapter';
// import './Facade';
// import './TemplateMethod';
import './Iterator';
